Add Same() and Walk() functions
VRublevski/binary-tree pull request #1
Opened 2020-12-28 12:26 UTC by VRublevski

2020-12-29 07:10 UTC, papahmsolo requested changes
Looks good!
- In the `New()` We should probably range over the input and call some func like `insert(i int)`
- We can have a single channel to send values to in `Walk`, I'm not sure we need to walk left and right tree in the new goroutine.

2020-12-29 07:10 UTC, papahmsolo commented on tree_test.go
> +	}
This test looks good. If we have in the test table also an expected slice we should get after we walk the tree, you won't need to assertSorted, you can simply deepEqual what we got and what we expect

2020-12-29 08:30 UTC, VRublevski commented on tree.go
> +}
@papahmsolo The `insert()` function was not mentioned in the exercise. So I decided that it would be sufficient to have only a function that builds an immutable tree. The tree is not balanced as I understand and if we simply loop and `insert()` it could be the case that the tree would become a linked list. And I think that the way I build the tree that it will be more or less balanced. I had implementation where I sorted the input to have the property of a search tree each time it was called recursively, but I found that it's sufficient to sort the input once.

2020-12-29 08:54 UTC, VRublevski commented on tree_test.go
> +	}
@papahmsolo Yes, you are right. It's much simpler. I made the suggested changes.

2020-12-29 09:00 UTC, VRublevski commented on tree.go
> +}
@papahmsolo Now I use a single goroutine to traverse the `Tree`. It was not clear for me how to close the channel only once at first.

2020-12-29 10:13 UTC, VRublevski commented
@papahmsolo I've changed `New()` and `Same()` functions. Please, leave your comment about them.

2020-12-29 16:23 UTC, papahmsolo requested changes
Cool, let's fix some issues and move on!

2020-12-29 16:23 UTC, papahmsolo commented on tree.go
> +	root := new(*Tree)
`new` returns a pointer to a type, so in this case you'll return a pointer to a pointer of the type `Tree`
https://golang.org/doc/effective_go.html#allocation_new

2020-12-29 16:23 UTC, papahmsolo commented on tree.go
> +	for node != nil {
We can avoid passing the node to `insert` as we can create it inside and return after that. We'll only need the parent (or root) node and the value we want to insert.

2020-12-29 16:23 UTC, papahmsolo commented on tree.go
> +	}
Do we need to check `t.Left` and `t.Right` for nil?

2020-12-29 17:34 UTC, VRublevski commented on tree.go
> +	root := new(*Tree)
@papahmsolo I dereference root which is `**Tree` before return, so it's of the type `*Tree`

2020-12-29 17:36 UTC, VRublevski commented on tree.go
> +	for node != nil {
@papahmsolo That's true. Now `insert` requires only `root` and `val` as parameters.

2020-12-29 17:39 UTC, VRublevski commented on tree.go
> +	}
@papahmsolo You're right, these checks are redundant. So I dropped them.

2020-12-30 09:26 UTC, VRublevski commented on tree.go
> +	root := new(*Tree)
@papahmsolo I use `*Tree` as a return type of insert now, so that I'm able to return root and get rid of pointer to pointer.

2020-12-30 10:42 UTC, papahmsolo reviewed
With recursion, this could look a bit more readable
```
func insert(t *Tree, v int) *Tree {
	if t == nil {
		return &Tree{nil, v, nil}
	}
	if v < t.Value {
		t.Left = insert(t.Left, v)
	} else {
		t.Right = insert(t.Right, v)
	}
	return t
}
```
I'm not asking you to change anything, your implementation is fine. Just FYI

2020-12-30 10:42 UTC, papahmsolo commented on tree.go
> +	}
Oneliner would look a bit better `newNode := &Tree{Value: val}`

2020-12-30 10:49 UTC, papahmsolo requested changes
Let's also add the test for a different sequence of ints but the same values

2020-12-30 11:08 UTC, VRublevski commented on tree.go
> +	}
@papahmsolo Now it can please eyes.

2020-12-30 13:27 UTC, VRublevski commented
@papahmsolo I've formatted source code and added benchmark for same. Can you have a look, please?

2020-12-30 18:12 UTC, papahmsolo requested changes
Looks very good!

2020-12-30 18:12 UTC, papahmsolo commented on tree.go
> +	return
I know, it's not necessary, but I return values explicitly `return root`. So that you don't have to go to a func declaration to see what's being returned.

2020-12-30 18:12 UTC, papahmsolo commented on tree_test.go
> +	nElements := 10000
We can make it a constant if it does not change. `const num = 10000`

2020-12-30 18:12 UTC, papahmsolo commented on tree_test.go
> +		treeB := New(bPerm...)
We don't have to create variables if we don't really need them, do we?
`New(r.Perm(nElements)...)`

2020-12-30 18:12 UTC, papahmsolo commented on tree_test.go
> +		}
Same here:
`if !Same(treeA, treeB)`
you can even read it like prose - if not Same :)

2020-12-31 08:34 UTC, VRublevski commented on tree_test.go
> +	nElements := 10000
@papahmsolo It really does not change, so now it's a constant.

2020-12-31 08:36 UTC, VRublevski commented on tree_test.go
> +		treeB := New(bPerm...)
@papahmsolo I thought that it adds clarity, but now I understand this is not the case. I've got rid of them.

2020-12-31 08:37 UTC, VRublevski commented on tree_test.go
> +		}
@papahmsolo Maybe we will write a book one day:)

2021-01-04 07:45 UTC, papahmsolo approved these changes
Looks good!

2021-01-04 07:45 UTC, merged